#!/bin/sh
set -eu

mariadb --protocol=socket -uroot -p"$MARIADB_ROOT_PASSWORD" "$MARIADB_DATABASE" <<SQL
GRANT SELECT ON ${MARIADB_DATABASE}.fact_decision_feature_snapshot TO '$MARIADB_APP_USER'@'%';
GRANT SELECT ON ${MARIADB_DATABASE}.fact_decision_label TO '$MARIADB_APP_USER'@'%';
GRANT SELECT ON ${MARIADB_DATABASE}.decision_model_registry TO '$MARIADB_APP_USER'@'%';
GRANT SELECT ON ${MARIADB_DATABASE}.fact_decision_model_prediction TO '$MARIADB_APP_USER'@'%';

GRANT SELECT, INSERT, UPDATE ON ${MARIADB_DATABASE}.fact_decision_feature_snapshot TO '$MARIADB_PUBLISH_USER'@'%';
GRANT SELECT, INSERT, UPDATE ON ${MARIADB_DATABASE}.fact_decision_label TO '$MARIADB_PUBLISH_USER'@'%';
GRANT SELECT, INSERT, UPDATE ON ${MARIADB_DATABASE}.decision_model_registry TO '$MARIADB_PUBLISH_USER'@'%';
GRANT SELECT, INSERT, UPDATE ON ${MARIADB_DATABASE}.fact_decision_model_prediction TO '$MARIADB_PUBLISH_USER'@'%';
GRANT SELECT, INSERT, UPDATE ON ${MARIADB_DATABASE}.shadow_mode_status TO '$MARIADB_PUBLISH_USER'@'%';
FLUSH PRIVILEGES;
SQL
