server {
    listen 18080;

    location / {
        proxy_pass http://spark-master:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 18081;

    location / {
        proxy_pass http://spark-worker:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
