FROM nginx:1.27.5-alpine

COPY infrastructure/nginx/web-app.conf /etc/nginx/conf.d/default.conf
COPY web/index.html /usr/share/nginx/html/index.html
COPY web/styles.css /usr/share/nginx/html/styles.css
COPY web/app.js /usr/share/nginx/html/app.js
